version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: mood
      POSTGRES_PASSWORD: mood
      POSTGRES_DB: moodmacth
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
